name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        wget https://jenkins.pmmp.io/job/PHP-7.3-Aggregate/lastSuccessfulBuild/artifact/PHP-7.3-Linux-x86_64.tar.gz
        tar -xzf PHP-7.3-Linux-x86_64.tar.gz
        wget https://getcomposer.org/download/1.9.1/composer.phar
        bin/php7/bin/php composer.phar install
        mkdir plugins
        cd plugins
        wget https://poggit.pmmp.io/r/68109/PocketMine-DevTools.phar
        cd
        ./start.sh
        eng
        y
        y
        makeserver
        stop
